Update to new osl-firewall resources
osuosl-cookbooks/osl-imap pull request #16
Opened 2021-02-04 02:07 UTC by detjensrobert

2021-02-24 18:03 UTC, ramereth requested changes

2021-02-24 18:03 UTC, ramereth commented on envvars
> -pr_link=https://github.com/osuosl-cookbooks/osl-imap/pull/1
Let's not remove this as I think it may cause an issue.

2021-02-25 18:16 UTC, ramereth commented
@detjensrobert can you please resolve the failures?

2021-02-27 00:03 UTC, ramereth approved these changes

2021-03-02 01:34 UTC, detjensrobert commented
![](https://github.trello.services/images/mini-trello-icon.png) [osl-imap](https://trello.com/c/Dy2PApNi/2114-osl-imap)

2021-05-25 20:49 UTC, detjensrobert commented
!bump major

2021-05-25 20:49 UTC, merged

2021-05-25 20:49 UTC, osuosl-manatee commented
Jenkins has merged this PR into `master` and has automatically performed a major-level version bump to v2.0.0.  Have a nice day!