Ported integration test to osl_mysql_test resource
osuosl-cookbooks/osl-imap pull request #23
Opened 2023-03-03 21:26 UTC by sectopodwreck

***Warning***: It seems that the `Dovecot` cookbook we are using is relying on the deprecated `ohai` cookbook. I've had to suppress deprecations as errors in order for this to converge properly.

I see a previous user was attempting to fix this issue in PR #22.

2023-05-17 17:22 UTC, ramereth requested changes

2023-05-17 17:22 UTC, ramereth commented on kitchen.yml
> +  # deprecations_as_errors: true
Just change this to false and add a comment as to why

2023-05-17 21:24 UTC, ramereth approved these changes
Patch bump

2023-05-17 21:33 UTC, sectopodwreck commented
!bump patch ~

2023-05-17 21:33 UTC, merged

2023-05-17 21:33 UTC, osuosl-manatee commented
Jenkins has merged this PR into `master` and has automatically performed a patch-level version bump to v2.0.3.  Have a nice day!

2023-05-18 17:22 UTC, sectopodwreck commented
Accidental push, ignore.